import mongoose from "mongoose";
 
import {randomUUID} from "crypto";  // it is used to create the id

const chatSchema = new mongoose.Schema({
    // id is automatically provide by db but we can also create id
    id:{
        type : String,
        default : randomUUID(),
    },
    role:{
        type : String,
        required : true,
    },
    content : {
        type : String,
        required : true,
    }
});

const userSchema = new mongoose.Schema({
    // id is automatically generated by the db
    name : {
        type : String,
        required : true,
    },
    email:{
        type:String,
        required : true,
        unique : true,
    },
    password : {
        type:String,
        required : true,
    },
    chats:[chatSchema],
});

export default mongoose.model("User",userSchema);